server:
  port: 10086
  servlet:
    context-path: /api
spring:
  application:
    name: food-share-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1234
